### ISSUE TITLE
Chris Checking In

### ISSUE THREAD

**Issue by chrissyrenslow** [JamesNewton/ProgramYourFutureIntro#1]
Hello my name is Christopher Renslow, although I'd prefer to be called Chris. The goal that I'm seeking out to achieve in this class is to learn as much as cybersecurity as I possibly can. My email address is renslow.chris@gmail.com and is the fastest way, excluding a text/phone call, to reach me. I am very happy to be in this class and I look forward to getting to know you all.

**Comment by JamesNewton** [comment]
Hey Chris, I know you have done some impressive programming, any chance you will share some of it on your repo? Your notes are a hoot:
https://github.com/chrissyrenslow/RenslowNotes/wiki/A-Place-In-Which-Notes-Are-Kept
(yes, I'm old enough to say something is a "hoot") but they are more entertaining than informative. Perhaps you can extend them to write tutorials from the Shrek point of view?

**Comment by chrissyrenslow** [comment]
I just noticed this and may I just say you've been a great instructor. I understand that today's instruction/class is based on the presentations being presented to the staff members and faculty involved in the app development. I was wondering with your permission if I am able to be allowed to miss the last day of class in order to spend time with my family while knowing that today will be focused on presentation?

**Comment by JamesNewton** [comment]
Sorry, I just saw this. Really glad you stayed and did a presentation!

Thank you for attending and being a good student. When you have time, please respond to this survey:
https://ucsdextension.co1.qualtrics.com/jfe/form/SV_54tvnx9bMBgGgol 
and **applications for the certificate classes will be available here:
https://extension.ucsd.edu/program-your-future
I'm told the deadline for this is today!** Please hurry and apply even if you don't see this in time, and email mvowleslancaster@ucsd.edu for clarification.
