### ISSUE TITLE
eli check in

### ISSUE THREAD

**Issue by eliyoung123** [JamesNewton/ProgramYourFutureIntro#14]
hello im good

**Comment by JamesNewton** [comment]
Hi Eli, can you share what you want to get out of the class? 

Please also try to catch up before next Sunday as the class will be going faster. Follow the Day 1 and Day 2 pages here:
https://github.com/JamesNewton/ProgramYourFutureIntro/wiki

**Comment by JamesNewton** [comment]
Thank you for attending and being a good student. When you have time, please respond to this survey:
https://ucsdextension.co1.qualtrics.com/jfe/form/SV_54tvnx9bMBgGgol 
and **applications for the certificate classes will be available here:
https://extension.ucsd.edu/program-your-future
I'm told the deadline for this is today!** Please hurry and apply even if you don't see this in time, and email mvowleslancaster@ucsd.edu for clarification.

**Comment by eliyoung123** [comment]
Dear Mr. Newton,

Sry for not being as invested before, I didn't understand it completely and was kind of afraid to ask questions so I just trailed further and further behind. I need to work on asking questions and seeing the importance of things so I can be more devoted. I filled out the survey and apparently, my father submitted the application for me. I would like to keep in touch with you as a mentor in case I have any questions in the future, so what is your email? Also, please hit me up with an email if there is anything important you would like to share with me later on.

My email: elidodsontablet@gmail.com

(ugh I need a new email, haha)

Thanks,
Eli Young
