### ISSUE TITLE
Carmen checking in

### ISSUE THREAD

**Issue by carmencamacho1** [JamesNewton/ProgramYourFutureIntro#15]
I am here because because I have great interest in programming. What I hope to get out of this program is to be able to create apps and learn a language other than java.

**Comment by JamesNewton** [comment]
Thanks for checking in. Can you please do the Day 1 Block 1 stuff starting on step 4. <BR>
https://github.com/JamesNewton/ProgramYourFutureIntro/wiki/Day-1#block-1-introduction-accounts-goals-1pm-to-230

Basically just make a new repo for this class and in it, open the WiKi and learn how to use it to take notes.
