### ISSUE TITLE
Alexandra Lim checking in

### ISSUE THREAD

**Issue by AlexandraLim** [JamesNewton/ProgramYourFutureIntro#16]
I just want to see if coding is the right thing for me to do. Moreover, I'm still deciding what my intended major is.

**Comment by JamesNewton** [comment]
Very impressive notes:
https://github.com/AlexandraLim/Program-Your-Future/wiki

**Comment by JamesNewton** [comment]
Thank you for attending and being a good student. When you have time, please respond to this survey:
https://ucsdextension.co1.qualtrics.com/jfe/form/SV_54tvnx9bMBgGgol 
and **applications for the certificate classes will be available here:
https://extension.ucsd.edu/program-your-future
I'm told the deadline for this is today!** Please hurry and apply even if you don't see this in time, and email mvowleslancaster@ucsd.edu for clarification.

Don't hesitate to raise an issue here if you need a recommendation or referral.
