### ISSUE TITLE
Roel T. Checking in

### ISSUE THREAD

**Issue by rdt521** [JamesNewton/ProgramYourFutureIntro#17]
The canvas in the app inventor is basically the same thing as it sounds where you put things onto it and it acts like a grid.
The canvas can be used for games or drawing pictures on it and stuff

**Comment by JamesNewton** [comment]
All true and thank you for checking in. But please reply below with what you expect from the class, and keep notes about what you learn on your own wiki here:
https://github.com/rdt521/rdt2/wiki

**Comment by JamesNewton** [comment]
Thank you for attending and being a good student. When you have time, please respond to this survey:
https://ucsdextension.co1.qualtrics.com/jfe/form/SV_54tvnx9bMBgGgol 
and **applications for the certificate classes will be available here:
https://extension.ucsd.edu/program-your-future
I'm told the deadline for this is today!** Please hurry and apply even if you don't see this in time, and email mvowleslancaster@ucsd.edu for clarification.

Don't hesitate to raise an issue here if you need a recommendation or referral.
