### ISSUE TITLE
Marco Paredes checking in

### ISSUE THREAD

**Issue by mparedes3** [JamesNewton/ProgramYourFutureIntro#2]
Marco Paredes

I am here to learn more about programming and how to apply it to the real world. I am hoping to gain a better insight of coding and assist me with my goal to get a job in it. I am interested in web-development and Android application programming.

**Comment by JamesNewton** [comment]
Very impressive notes!
https://github.com/mparedes3/NotesForProgramYourFuture/wiki/Notes

**Comment by JamesNewton** [comment]
Thank you for attending and being a good student. When you have time, please respond to this survey:
https://ucsdextension.co1.qualtrics.com/jfe/form/SV_54tvnx9bMBgGgol 
and **applications for the certificate classes will be available here:
https://extension.ucsd.edu/program-your-future
I'm told the deadline for this is today!** Please hurry and apply even if you don't see this in time, and email mvowleslancaster@ucsd.edu for clarification.

Don't hesitate to raise an issue here if you need a recommendation or referral.
