### ISSUE TITLE
eli chck in

### ISSUE THREAD

**Issue by eliyoung123** [JamesNewton/ProgramYourFutureIntro#20]

**Comment by JamesNewton** [comment]
Thank Eli, but you don't need to check in every week. Please do try to take more notes in your own GitHub wiki and I wish you all the best.

**Comment by eliyoung123** [comment]
How often should I check in?

**Comment by JamesNewton** [comment]
Only one checkin was needed. Raise another issue here if you have questions, concerns, ideas, etc...
