### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by eliyoung123** [JamesNewton/ProgramYourFutureIntro#23]
I understood it until I got to the actual coding part and then I got really confused:

https://www.youtube.com/watch?v=-zIBlg-I5BY

To start, right away, I don't understand the thing at the bottom or the playground or the print or anything past then in the video.

**Comment by JamesNewton** [comment]
Thanks for asking! And for pointing out the part where you stopped understanding.

When you say "thing at the bottom" you mean the box below the blue "play" button where the "hello playground" appears? That is the output area, where the results from the program above are displayed. Whatever you type in the editor is automatically run (in other words, "evaluated") and the result of that is put into that bottom box. 

Imagine that you have a pair of one way doors... to communicate with a person (the XCode compiler). One door only takes things from you and gives it to him (that's the top) and the other door only takes back stuff from him and gives it to you (bottom door).

You give instructions, the computer compiles that, executes the compiled instructions, and puts the output in that lower window. 

So, one of those instructions is "print." It really means "say" or "write" or "display" but back in the olden days, computers were hooked up to paper printers, so somehow we got stuck with "print". Whatever you had to print as a parameter, the computer will put in the output window. So if you say `print("Hello, playground")` you will see `Hello, playground` in the output. 

Remember from my notes before, a variable is just a box that holds something; a number, a message, a map, an object, whatever. The variable gets a name, just like you put a label on a box. In this case, the box is labeled "str" and it's had a message, "Hello, playground" put into it. So if we say `print(str)` in the top window, the computer takes that, looks inside the box labeled str and pulls out the message "Hello, playground" and prints it. 

It's literally a way to have a conversation with the computer. You "speak" (type) in the top box, using the Swift language, and the computer responds in the bottom box with it's best understanding of what you told it to do. 

Does that make sense? Don't hesitate to say no, but please explain what part of it doesn't make sense, or what was the last thing that did make sense.
