### ISSUE TITLE
Tania L

### ISSUE THREAD

**Issue by TaniaL17** [JamesNewton/ProgramYourFutureIntro#24]
I am one of your students from a coding class at Malcolm X and I don't have a way of contacting you for a question I have.

**Comment by JamesNewton** [comment]
Contact me right here, and ask your questions here please. I don't need students emails or contact outside the class except via github. 

Please open a new issue, and put your question in the main box, then summarize the question into the fewest possible words in the Title. I'll answer ASAP and that way, others can use the question and the answer as well.

**Comment by JamesNewton** [comment]
I should also say that if the question has to do with attendance, personal issues, or anything other than class related content problems, please email mvowleslancaster@ucsd.edu as Megan is in charge of the program and is better able to handle those questions.
