### ISSUE TITLE
Michelle checking in

### ISSUE THREAD

**Issue by coder263** [JamesNewton/ProgramYourFutureIntro#3]
Name: Michelle 

Motivation: I am attending this course in hopes of reinforcing my knowledge of basic programming languages and learning new ways of condensing code. I want to do biomedical research in the future, therefore I do want to learn basic programming in order to be able to perform things like protein modulation in the future.

**Comment by JamesNewton** [comment]
Great notes!

**Comment by JamesNewton** [comment]
Thank you for attending and being a good student. When you have time, please respond to this survey:
https://ucsdextension.co1.qualtrics.com/jfe/form/SV_54tvnx9bMBgGgol 
and **applications for the certificate classes will be available here:
https://extension.ucsd.edu/program-your-future
I'm told the deadline for this is today!** Please hurry and apply even if you don't see this in time, and email mvowleslancaster@ucsd.edu for clarification.

Don't hesitate to raise an issue here if you need a recommendation or referral.
