### ISSUE TITLE
Letter of Recommendation

### ISSUE THREAD

**Issue by SummerFlu** [JamesNewton/ProgramYourFutureIntro#34]
Hi Mr.Newton, This is Anson Lee, a previous student of yours from the Program Your Future program. I was hoping if it is possible for you to write a letter of recommendation for me for a navy internship: https://nreip.asee.org/. I know we didn't have too much time to get to know each other but I would appreciate if you would help me with this task. I plan to major into computer science and I have a passion for programming. Thanks for your consideration! Let me know if you have any questions.

**Comment by JamesNewton** [comment]
More than happy to sign off / collaborate on a letter of recommendation for you. Can you let me know what they are looking for, or what you want the letter to say?

**Comment by SummerFlu** [comment]
I'd like it if it would emphasized my technical skills such as through programming and other traits that would make me the best candidate for the program. The internship is for engineering and science and I'd like to one day pursue it though programming. The application is due next Friday and I apologize for the late notice.

**Comment by JamesNewton** [comment]
To whom it may concern,

I recently had the pleasure of teaching a class for UCSD Extension at the Malcolm X library in San Diego and one of the students in that class deserves special mention; Anson ("SummerFlu") Lee. Mr. Lee proved himself to be very technically competent, and a real asset to the class and instructor (myself). He was able to resolve a problem with GitHub and the iOS Swift development system which allowed several other students in the class to recover from the loss of their prior work and continue on par with the class.  His attention to detail and quick thinking were evident not only in that instance, but in small ways throughout the course of the instruction. He also showed up early or on time and paid attention throughout each class day. I have no hesitation in recommending him for an internship or other entry level position with any company or organization. 

James Newton
@MassMind.org
