### ISSUE TITLE
Rachel checking in

### ISSUE THREAD

**Issue by rhartanto234** [JamesNewton/ProgramYourFutureIntro#4]
Rachel Hartanto

Hello, I'm here because this seemed like a very good opportunity to see how the things we see every day on the internet work and what kind of work goes into it. I think it's an interesting topic to learn more about.

**Comment by JamesNewton** [comment]
Excellent! Your FFFF summary is perfect.

**Comment by JamesNewton** [comment]
Excellent notes:
https://github.com/rhartanto234/Notes234/wiki

**Comment by JamesNewton** [comment]
Thank you for attending and being a good student. When you have time, please respond to this survey:
https://ucsdextension.co1.qualtrics.com/jfe/form/SV_54tvnx9bMBgGgol 
and **applications for the certificate classes will be available here:
https://extension.ucsd.edu/program-your-future
I'm told the deadline for this is today!** Please hurry and apply even if you don't see this in time, and email mvowleslancaster@ucsd.edu for clarification.

Don't hesitate to raise an issue here if you need a recommendation or referral.
